"""created new column in doctors

Revision ID: 36a65470de6c
Revises: 8a2ccec82ca8
Create Date: 2023-10-23 18:30:09.488530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a65470de6c'
down_revision: Union[str, None] = '8a2ccec82ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('extension', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'extension')
    # ### end Alembic commands ###
